### ISSUE TITLE
Central Khmer Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/km.reactjs.org#1]
## Maintainer Team

* @Bunlong
* @lengsovandara
* @BunHouth 
* @parinha  
* @hengsovandara
* @Choengteur  
* @bunlongoung
* @ks-nireak
* @NySiya 

## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find find that you can't commit any more, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [ ] Home Page (@tesseralis) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [x] Home Page (@Bunlong) #2 
* [x] Tutorial (@Bunlong) #3  

### Basics

* [x] Hello World (@lengsovandara) #6 
* [x] Introducing JSX (@BunHouth) #7 
* [x] Rendering Elements (@BunHouth) #9 
* [x] Components and Props (@BunHouth) #11
* [x] State and Lifecycle(@BunHouth) #12 
* [ ] Handling Events (@Bunlong) (@lengsovandara ) #22
* [x] Conditional Rendering (@Bunlong) #32 
* [x] Lists and Keys (@Bunlong) #34 
* [x] Forms (@Bunlong) #36 
* [x] Lifting State Up (@Bunlong) #40 
* [ ] Composition vs Inheritance (@Bunlong) (@BunHouth) #43
* [x] Thinking in React (@Bunlong) #53 

### API Reference

* [ ] React (@Bunlong) (@bunlongoung)
* [ ] React.Component
* [ ] ReactDOM
* [ ] ReactDOMServer
* [ ] DOM Elements
* [ ] SyntheticEvent
* [ ] Test Utilities
* [ ] Shallow Renderer
* [ ] Test Renderer
* [ ] JS Environment Requirements
* [ ] Glossary

### Navigation

These are the navigation links that appears in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [ ] tutorial/nav.yml
* [ ] docs/nav.yml

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [x] Getting Started (@Bunlong) #20 
* [x] Add React to a Website (@Bunlong) #26 
* [x] Create a New React App (@Bunlong) #28 
* [x] CDN Links (@Bunlong) #30 

### Hooks

Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.

  * [x] Introducing Hooks (@parinha)
  * [x] Hooks at a Glance (@Bunlong) #108
  * [x] Using the State Hook (@Bunlong) #116
  * [x] Using the Effect Hook (@Bunlong) #118 
  * [x] Rules of Hooks (@Bunlong) #123
  * [x] Building Your Own Hooks (@Bunlong) #125
  * [ ] Hooks API Reference (@Bunlong) #127
  * [ ] Hooks FAQ

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [x] dont-call-proptypes (@ks-nireak)
* [ ] invalid-aria-prop
* [ ] invalid-hook-call-warning
* [ ] legacy-factories
* [ ] refs-must-have-owner
* [ ] special-props
* [ ] unknown-prop

### Advanced Guides

* [x] Accessibility (@hengsovandara)
* [ ] Code-Splitting
* [ ] Context
* [ ] Error Boundaries
* [ ] Forwarding Refs
* [ ] Fragments
* [ ] Higher-Order Components
* [ ] Integrating with Other Libraries
* [ ] JSX In Depth
* [ ] Optimizing Performance
* [ ] Portals
* [ ] React Without ES6 (@Choengteur)
* [ ] React Without JSX
* [ ] Reconciliation
* [ ] Refs and the DOM
* [ ] Render Props
* [ ] Static Type Checking
* [ ] Strict Mode
* [ ] Typechecking With PropTypes
* [ ] Uncontrolled Components
* [ ] Web Components

### FAQ

* [ ] APIs and AJAX (@NySiya)
* [ ] Babel, JSX, and Build Steps
* [ ] Passing Functions to Components
* [ ] Component State
* [ ] Styling and CSS
* [ ] File Structure
* [ ] Versioning Policy
* [ ] Virtual DOM and Internals

### Contributing

Priority: Low

* [ ] How to Contribute
* [ ] Codebase Overview
* [ ] Implementation Notes
* [ ] Design Principles

### Components

Components in `src/components` that have some text in them.

* [ ] CodeEditor
* [ ] CodeExample
* [ ] ErrorDecoder
* [ ] LayoutFooter
* [ ] LayoutHeader
* [ ] MarkdownPage

## Additional Translations

These are not the primary translation targets.

* [ ] Blog
* [ ] Community

**Comment by tesseralis** [comment]
@Bunlong, @lengsovandara, please use this issue to track your progress!

**Comment by Bunlong** [comment]
@tesseralis Okay, we got it. Thank you!

**Comment by tesseralis** [comment]
@Bunlong please don't check the checkbox until the PR is merged! Thanks!

**Comment by Bunlong** [comment]
@tesseralis Okay, I got it. Thanks!

**Comment by toeurtenh** [comment]
interested in helping translate to khmer language, how can i help?

**Comment by tesseralis** [comment]
@toeurtenh respond to this issue with a page to translate, and create a pull request like [this one](https://github.com/reactjs/km.reactjs.org/pull/56).

**Comment by gaearon** [comment]
It looks like this translation has stalled, and is now outdated.
I'm going to archive this repo, but if someone wants to pick up, please start a new effort.
