### ISSUE TITLE
Translate Getting Started

### ISSUE THREAD

**Issue by Bunlong** [reactjs/km.reactjs.org#20]
### TODO

- [x] Getting Started
- [x] Try React
  * [x] Online Playgrounds
  * [x] Add React to a Website
  * [x] Create a New React App
- [x] Learn React
  * [x] First Examples
  * [x] React for Beginners
  * [x] React for Designers
  * [x] JavaScript Resources
  * [x] Practical Tutorial
  * [x] Step-by-Step Guide
  * [x] Thinking in React
  * [x] Recommended Courses
  * [x] Advanced Concepts
  * [x] API Reference
  * [x] Glossary and FAQ
- [x] Staying Informed
- [x] Versioned Documentation
- [x] Something Missing?
