### ISSUE TITLE
Translate Add React to a Website

### ISSUE THREAD

**Issue by Bunlong** [reactjs/km.reactjs.org#26]
### TODO

- [x] Add React to a Website
- [x] Add React in One Minute
  * [x] Step 1: Add a DOM Container to the HTML
  * [x] Step 2: Add the Script Tags
  * [x] Step 3: Create a React Component
  * [x] That’s It!
  * [x] Tip: Reuse a Component
  * [x] Tip: Minify JavaScript for Production
- [x] Optional: Try React with JSX
  * [x] Quickly Try JSX
  * [x] Add JSX to a Project
  * [x] Run JSX Preprocessor
