### ISSUE TITLE
Translate Create a New React App

### ISSUE THREAD

**Issue by Bunlong** [reactjs/km.reactjs.org#28]
### TODO

- [x] Create a New React App
- [x] You Might Not Need a Toolchain
- [x] Recommended Toolchains
  * [x] Create React App
  * [x] Next.js
  * [x] Gatsby
  * [x] More Flexible Toolchains
- [x] Creating a Toolchain from Scratch
