### ISSUE TITLE
Translate Conditional Rendering

### ISSUE THREAD

**Issue by Bunlong** [reactjs/km.reactjs.org#32]
### TODO

- [x] Conditional Rendering
  * [x] Element Variables
  * [x] Inline If with Logical && Operator
  * [x] Inline If-Else with Conditional Operator
  * [x] Preventing Component from Rendering
