### ISSUE TITLE
Translate Lists and Keys

### ISSUE THREAD

**Issue by Bunlong** [reactjs/km.reactjs.org#34]
### TODO

- [x] Lists and Keys
  * [x] Rendering Multiple Components
  * [x] Basic List Component
  * [x] Keys
    * [x] Extracting Components with Keys
    * [x] Keys Must Only Be Unique Among Siblings
    * [x] Embedding map() in JSX
