### ISSUE TITLE
Translate Forms

### ISSUE THREAD

**Issue by Bunlong** [reactjs/km.reactjs.org#36]
### TODO

- [x] Forms
  * [x] Controlled Components
  * [x] The textarea Tag
  * [x] The select Tag
  * [x] The file input Tag
  * [x] Handling Multiple Inputs
  * [x] Controlled Input Null Value
  * [x] Alternatives to Controlled Components
  * [x] Fully-Fledged Solutions
