### ISSUE TITLE
Translate Tutorial

### ISSUE THREAD

**Issue by Bunlong** [reactjs/km.reactjs.org#4]
### TODO

- [x] TUTORIAL
- [x] Before We Start the Tutorial
  * [x] What Are We Building?
  * [x] Prerequisites
- [x] Setup for the Tutorial
  * [x] Option 1: Write Code in the Browser
  * [x] Option 2: Local Development Environment
  * [x] Help, I'm Stuck!
- [x] Overview
  * [x] What Is React?
  * [x] Inspecting the Starter Code
  * [x] Passing Data Through Props
  * [x] Making an Interactive Component
  * [x] Developer Tools
- [x] Completing the Game
  * [x] Lifting State Up
  * [x] Why Immutability Is Important
  * [x] Function Components
  * [x] Taking Turns
  * [x] Declaring a Winner
- [x] Adding Time Travel
  * [x] Storing a History of Moves
  * [x] Lifting State Up, Again
  * [x] Showing the Past Moves
  * [x] Picking a Key
  * [x] Implementing Time Travel
  * [x] Wrapping Up
