### ISSUE TITLE
Translate Lifting State Up

### ISSUE THREAD

**Issue by Bunlong** [reactjs/km.reactjs.org#40]
### TODO

- [x] Lifting State Up
  * [x] Adding a Second Input
  * [x] Writing Conversion Functions
  * [x] Lifting State Up
  * [x] Lessons Learned
